from ex2.creatures import CreatureFactory, FlameFactory, AquaFactory
from ex2.creatures import HealingCreatureFactory, TransformCreatureFactory
from ex2.battle_strategy import BattleStrategy, NormalStrategy
from ex2.battle_strategy import AggressiveStrategy, DefensiveStrategy


CreatureFactory
FlameFactory
AquaFactory
HealingCreatureFactory
TransformCreatureFactory
BattleStrategy
NormalStrategy
AggressiveStrategy
DefensiveStrategy
