from ex1.creature_factories import CreatureFactory, HealingCreatureFactory
from ex1.creature_factories import TransformCreatureFactory

CreatureFactory
HealingCreatureFactory
TransformCreatureFactory
